name: Update Recent News

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run news update script
        env:
          NEWS_API_TOKEN: ${{ secrets.NEWS_API_TOKEN }}
        run: python scripts/update_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add recent-news.html
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m 'Automated update of recent news stories'
            git push
          else
            echo "No changes to commit."
          fi
