name: Update News Articles (Brave API)

on:
  schedule:
    # Runs every 6 hours (adjust as needed)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  update-news-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script for Recent News
        env:
          BRAVE_NEWS_API_KEY: ${{ secrets.BRAVE_NEWS_API_KEY }}
        run: |
          python scripts/update_news.py \
            --html_file_name "recent-news.html" \
            --query "recent political news" \
            --api_locale "us" \
            --featured_div_identifier "#smart-grid" \
            --max_articles 10

      - name: Run script for International News
        env:
          BRAVE_NEWS_API_KEY: ${{ secrets.BRAVE_NEWS_API_KEY }}
        run: |
          python scripts/update_news.py \
            --html_file_name "international-news.html" \
            --query "international news" \
            --api_locale "gb,ca,au" \
            --featured_div_identifier ".featured-news" \
            --max_articles 10
            
      - name: Run script for AI News
        env:
          BRAVE_NEWS_API_KEY: ${{ secrets.BRAVE_NEWS_API_KEY }}
        run: |
          python scripts/update_news.py \
            --html_file_name "ai-news.html" \
            --query "recent ai news" \
            --api_locale "us,gb" \
            --featured_div_identifier ".featured-news" \
            --max_articles 10

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add recent-news.html international-news.html ai-news.html
          if ! git diff --staged --quiet; then
            git commit -m "Automated news update via Brave API"
            git push
          else
            echo "No changes to commit for news files."
          fi
